// ---------------------------------------------------------------------------
// Generator — the "describe an app → get files" seam (Builder mode).
//
// Today it is a deterministic, template-based scaffolder: a prompt is routed to
// a template by keyword, and it emits REAL, self-contained files that render in
// the preview with no build step and are editable/browsable like any workspace
// file. The signature (prompt → files) is exactly what an LLM code-gen backend
// would fill; swapping this function for a model call is the only change needed.
// ---------------------------------------------------------------------------

export interface Generated {
	name: string;
	slug: string;
	kind: string;
	/** All files written to the workspace, path → contents. */
	files: Record<string, string>;
	/** The self-contained HTML entry used for the live preview. */
	entry: string;
}

function slugify(s: string): string {
	return (
		s
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, '-')
			.replace(/^-+|-+$/g, '')
			.slice(0, 32) || 'app'
	);
}

function page(title: string, body: string, style: string, script = ''): string {
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
*{box-sizing:border-box}body{margin:0;font:16px/1.6 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif;color:#18181b;background:#fff}
a{color:inherit}.wrap{max-width:1040px;margin:0 auto;padding:0 24px}
${style}
</style>
</head>
<body>
${body}
${script ? `<script>${script}</script>` : ''}
</body>
</html>`;
}

function landing(prompt: string): { title: string; entry: string } {
	const title = prompt.replace(/\b(landing|page|site|website|for|a|an|the)\b/gi, '').trim() || 'Nova';
	const name = title.split(/\s+/).slice(0, 2).join(' ') || 'Nova';
	const body = `<header class="nav"><div class="wrap row"><b>${name}</b><nav><a>Features</a><a>Pricing</a><a>Docs</a><a class="cta">Get started</a></nav></div></header>
<section class="hero"><div class="wrap">
  <span class="pill">New · v1.0</span>
  <h1>${name} ships faster.</h1>
  <p>${prompt.trim()}. A clean, fast starting point generated by Velocity — edit it live, preview instantly, deploy anywhere.</p>
  <div class="row gap"><a class="cta">Start free</a><a class="ghost">Live demo →</a></div>
</div></section>
<section class="wrap grid">
  <div class="card"><h3>Fast</h3><p>Sub-second interactions, no bloat.</p></div>
  <div class="card"><h3>Composable</h3><p>Bring your own stack and data.</p></div>
  <div class="card"><h3>Open</h3><p>Own the code. Deploy anywhere.</p></div>
</section>
<footer class="wrap">© ${name}. Built with Velocity.</footer>`;
	const style = `.row{display:flex;align-items:center;justify-content:space-between;gap:16px}.gap{gap:12px;justify-content:flex-start}
.nav{border-bottom:1px solid #ececf0;padding:14px 0}nav a{margin-left:20px;color:#52525b;text-decoration:none;font-size:14px;cursor:pointer}
.cta{background:#5b5bd6;color:#fff!important;padding:9px 16px;border-radius:9px;font-weight:600}.ghost{padding:9px 16px;border:1px solid #d4d4d8;border-radius:9px}
.hero{padding:88px 0;text-align:center;background:radial-gradient(60% 120% at 50% 0,rgba(91,91,214,.12),transparent)}
.pill{display:inline-block;font-size:12px;color:#5b5bd6;border:1px solid #d6d6f5;border-radius:20px;padding:4px 12px;margin-bottom:18px}
.hero h1{font-size:52px;letter-spacing:-.03em;margin:0 0 14px}.hero p{max-width:56ch;margin:0 auto 26px;color:#52525b;font-size:18px}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:24px}.card{border:1px solid #ececf0;border-radius:14px;padding:22px}
.card h3{margin:0 0 6px}.card p{margin:0;color:#52525b}footer{padding:40px 24px;color:#a1a1aa;text-align:center}`;
	return { title: `${name} — landing`, entry: page(`${name}`, body, style) };
}

function todo(_prompt: string): { title: string; entry: string } {
	const body = `<div class="wrap app"><h1>Tasks</h1>
<form id="f"><input id="i" placeholder="What needs doing?" autocomplete="off" /><button>Add</button></form>
<ul id="l"></ul></div>`;
	const style = `.app{max-width:34rem;margin:56px auto}h1{font-size:30px;letter-spacing:-.02em}
form{display:flex;gap:8px;margin:16px 0}input{flex:1;padding:11px 13px;border:1px solid #d4d4d8;border-radius:10px;font:inherit}
button{padding:11px 16px;border:0;border-radius:10px;background:#5b5bd6;color:#fff;font-weight:600;cursor:pointer}
ul{list-style:none;padding:0}li{display:flex;align-items:center;gap:10px;padding:11px 4px;border-bottom:1px solid #ececf0}
li.done span{opacity:.5;text-decoration:line-through}li input{flex:none}.x{margin-left:auto;color:#a1a1aa;cursor:pointer;background:none;border:0}`;
	const script = `const l=document.getElementById('l'),f=document.getElementById('f'),i=document.getElementById('i');
let todos=[{t:'Try the Velocity builder',d:true},{t:'Edit this generated app live',d:false}];
function render(){l.innerHTML='';todos.forEach((td,ix)=>{const li=document.createElement('li');if(td.d)li.className='done';
const c=document.createElement('input');c.type='checkbox';c.checked=td.d;c.onchange=()=>{td.d=!td.d;render()};
const s=document.createElement('span');s.textContent=td.t;const x=document.createElement('button');x.className='x';x.textContent='×';x.onclick=()=>{todos.splice(ix,1);render()};
li.append(c,s,x);l.appendChild(li)})}
f.onsubmit=e=>{e.preventDefault();const v=i.value.trim();if(v){todos.push({t:v,d:false});i.value='';render()}};render();`;
	return { title: 'Todo app', entry: page('Tasks', body, style, script) };
}

function dashboard(_prompt: string): { title: string; entry: string } {
	const body = `<div class="shell"><aside><b>Acme</b><nav><a class="on">Overview</a><a>Customers</a><a>Revenue</a><a>Settings</a></nav></aside>
<main><header><h1>Overview</h1><span class="who">bcw</span></header>
<section class="kpis"><div class="kpi"><span>Revenue</span><b>$48.2k</b><i class="up">▲ 12%</i></div>
<div class="kpi"><span>Active users</span><b>3,914</b><i class="up">▲ 4%</i></div>
<div class="kpi"><span>Churn</span><b>1.8%</b><i class="dn">▼ 0.3%</i></div></section>
<div class="panel"><h3>Weekly signups</h3><div class="bars">${[40, 62, 48, 80, 72, 96, 68].map((h) => `<i style="height:${h}%"></i>`).join('')}</div></div></main></div>`;
	const style = `body{background:#f6f7f9}.shell{display:flex;min-height:100vh}
aside{width:210px;background:#fff;border-right:1px solid #ececf0;padding:18px}aside b{display:block;margin-bottom:18px}
nav{display:flex;flex-direction:column;gap:2px}nav a{padding:8px 10px;border-radius:8px;color:#52525b;font-size:14px;cursor:pointer}nav a.on{background:#eef0ff;color:#5b5bd6;font-weight:600}
main{flex:1;padding:22px 28px}header{display:flex;justify-content:space-between;align-items:center}.who{width:30px;height:30px;border-radius:50%;background:#5b5bd6;color:#fff;display:grid;place-items:center;font-size:12px}
.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:18px 0}.kpi{background:#fff;border:1px solid #ececf0;border-radius:14px;padding:16px}
.kpi span{color:#71717a;font-size:13px}.kpi b{display:block;font-size:26px;margin:4px 0}.up{color:#16a34a;font-size:12px}.dn{color:#dc2626;font-size:12px}
.panel{background:#fff;border:1px solid #ececf0;border-radius:14px;padding:18px}.bars{display:flex;align-items:flex-end;gap:12px;height:180px;margin-top:12px}
.bars i{flex:1;background:linear-gradient(180deg,#7c7cf0,#5b5bd6);border-radius:6px 6px 0 0}`;
	return { title: 'Dashboard', entry: page('Dashboard', body, style) };
}

function starter(prompt: string): { title: string; entry: string } {
	const body = `<div class="wrap center"><span class="pill">Generated by Velocity</span>
<h1>${prompt.trim() || 'Your new app'}</h1>
<p>A clean starting point. Open the files in the editor, tweak, and watch this preview update. Deploy the static output anywhere.</p>
<div class="row"><a class="cta">Primary action</a><a class="ghost">Secondary</a></div></div>`;
	const style = `.center{max-width:44rem;margin:14vh auto;text-align:center}.pill{display:inline-block;font-size:12px;color:#5b5bd6;border:1px solid #d6d6f5;border-radius:20px;padding:4px 12px;margin-bottom:16px}
h1{font-size:44px;letter-spacing:-.03em;margin:0 0 12px}p{color:#52525b;font-size:18px;margin:0 auto 24px;max-width:52ch}
.row{display:flex;gap:12px;justify-content:center}.cta{background:#5b5bd6;color:#fff;padding:11px 18px;border-radius:10px;font-weight:600;cursor:pointer}.ghost{padding:11px 18px;border:1px solid #d4d4d8;border-radius:10px;cursor:pointer}`;
	return { title: 'App', entry: page('App', body, style) };
}

function route(prompt: string): { kind: string; make: (p: string) => { title: string; entry: string } } {
	const p = prompt.toLowerCase();
	if (/(todo|task|checklist|to-do)/.test(p)) {
		return { kind: 'todo app', make: todo };
	}
	if (/(dashboard|admin|analytics|metrics|chart)/.test(p)) {
		return { kind: 'dashboard', make: dashboard };
	}
	if (/(landing|marketing|saas|startup|waitlist|hero|product page)/.test(p)) {
		return { kind: 'landing page', make: landing };
	}
	return { kind: 'starter', make: starter };
}

/** Route a prompt to a template and emit real, self-contained files. */
export function generate(prompt: string): Generated {
	const { kind, make } = route(prompt);
	const { entry } = make(prompt);
	const slug = slugify(prompt || kind);
	const dir = `builds/${slug}`;
	const readme = `# ${slug}\n\nGenerated by Velocity from the prompt:\n\n> ${prompt.trim() || '(empty)'}\n\nKind: ${kind}. Open index.html in the editor, or preview it live.\n`;
	return {
		name: slug,
		slug,
		kind,
		entry,
		files: {
			[`${dir}/index.html`]: entry,
			[`${dir}/README.md`]: readme,
		},
	};
}
